// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"

	"github.com/sqlc-dev/pqtype"
)

type WhatsappDevice struct {
	ID          int64          `json:"id"`
	Number      string         `json:"number"`
	ContainerID string         `json:"container_id"`
	Endpoint    string         `json:"endpoint"`
	Version     sql.NullString `json:"version"`
	Active      bool           `json:"active"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
	UpdatedWho  sql.NullString `json:"updated_who"`
}

type WhatsappDeviceWebhook struct {
	ID        int64          `json:"id"`
	DeviceID  int64          `json:"device_id"`
	Number    string         `json:"number"`
	Phrase    string         `json:"phrase"`
	Url       string         `json:"url"`
	UrlMethod string         `json:"url_method"`
	Body      sql.NullString `json:"body"`
	Active    bool           `json:"active"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

type WhatsappEventLog struct {
	ID          int64                 `json:"id"`
	Number      string                `json:"number"`
	Ip          sql.NullString        `json:"ip"`
	Method      sql.NullString        `json:"method"`
	Endpoint    sql.NullString        `json:"endpoint"`
	UserAgent   sql.NullString        `json:"user_agent"`
	StatusCode  sql.NullString        `json:"status_code"`
	RequestBody pqtype.NullRawMessage `json:"request_body"`
	CreatedAt   time.Time             `json:"created_at"`
}
