// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: whatsapp_event_log.sql

package db

import (
	"context"
	"database/sql"

	"github.com/sqlc-dev/pqtype"
)

const insertEventLog = `-- name: InsertEventLog :exec
INSERT INTO whatsapp_event_log (number, ip, method, endpoint, user_agent, status_code, request_body)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertEventLogParams struct {
	Number      string                `json:"number"`
	Ip          sql.NullString        `json:"ip"`
	Method      sql.NullString        `json:"method"`
	Endpoint    sql.NullString        `json:"endpoint"`
	UserAgent   sql.NullString        `json:"user_agent"`
	StatusCode  sql.NullString        `json:"status_code"`
	RequestBody pqtype.NullRawMessage `json:"request_body"`
}

func (q *Queries) InsertEventLog(ctx context.Context, arg InsertEventLogParams) error {
	_, err := q.db.ExecContext(ctx, insertEventLog,
		arg.Number,
		arg.Ip,
		arg.Method,
		arg.Endpoint,
		arg.UserAgent,
		arg.StatusCode,
		arg.RequestBody,
	)
	return err
}

const listLastLogs = `-- name: ListLastLogs :many
SELECT id, number, ip, method, endpoint, user_agent, status_code, request_body, created_at
FROM whatsapp_event_log
ORDER BY created_at DESC
LIMIT $1
`

func (q *Queries) ListLastLogs(ctx context.Context, limit int32) ([]WhatsappEventLog, error) {
	rows, err := q.db.QueryContext(ctx, listLastLogs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WhatsappEventLog
	for rows.Next() {
		var i WhatsappEventLog
		if err := rows.Scan(
			&i.ID,
			&i.Number,
			&i.Ip,
			&i.Method,
			&i.Endpoint,
			&i.UserAgent,
			&i.StatusCode,
			&i.RequestBody,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLogsByNumber = `-- name: ListLogsByNumber :many
SELECT id, number, ip, method, endpoint, user_agent, status_code, request_body, created_at
FROM whatsapp_event_log
WHERE number = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListLogsByNumberParams struct {
	Number string `json:"number"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListLogsByNumber(ctx context.Context, arg ListLogsByNumberParams) ([]WhatsappEventLog, error) {
	rows, err := q.db.QueryContext(ctx, listLogsByNumber, arg.Number, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WhatsappEventLog
	for rows.Next() {
		var i WhatsappEventLog
		if err := rows.Scan(
			&i.ID,
			&i.Number,
			&i.Ip,
			&i.Method,
			&i.Endpoint,
			&i.UserAgent,
			&i.StatusCode,
			&i.RequestBody,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
