// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: whatsapp_device_webhook.sql

package db

import (
	"context"
	"database/sql"
)

const getWebhookByPhrase = `-- name: GetWebhookByPhrase :one
SELECT id, device_id, number, phrase, url, url_method, body, active, created_at, updated_at
FROM whatsapp_device_webhook
WHERE device_id = $1 
  AND number = $2 
  AND phrase = $3
  AND active = TRUE
`

type GetWebhookByPhraseParams struct {
	DeviceID int64  `json:"device_id"`
	Number   string `json:"number"`
	Phrase   string `json:"phrase"`
}

func (q *Queries) GetWebhookByPhrase(ctx context.Context, arg GetWebhookByPhraseParams) (WhatsappDeviceWebhook, error) {
	row := q.db.QueryRowContext(ctx, getWebhookByPhrase, arg.DeviceID, arg.Number, arg.Phrase)
	var i WhatsappDeviceWebhook
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.Number,
		&i.Phrase,
		&i.Url,
		&i.UrlMethod,
		&i.Body,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertWebhook = `-- name: InsertWebhook :exec
INSERT INTO whatsapp_device_webhook (device_id, number, phrase, url, url_method, active, body)
VALUES ($1, $2, $3, $4, $5, TRUE, $6)
ON CONFLICT (device_id, number, phrase, url, url_method, body) DO NOTHING
`

type InsertWebhookParams struct {
	DeviceID  int64          `json:"device_id"`
	Number    string         `json:"number"`
	Phrase    string         `json:"phrase"`
	Url       string         `json:"url"`
	UrlMethod string         `json:"url_method"`
	Body      sql.NullString `json:"body"`
}

func (q *Queries) InsertWebhook(ctx context.Context, arg InsertWebhookParams) error {
	_, err := q.db.ExecContext(ctx, insertWebhook,
		arg.DeviceID,
		arg.Number,
		arg.Phrase,
		arg.Url,
		arg.UrlMethod,
		arg.Body,
	)
	return err
}

const listWebhooksByDevice = `-- name: ListWebhooksByDevice :many
SELECT id, device_id, number, phrase, url, url_method, body, active, created_at, updated_at
FROM whatsapp_device_webhook
WHERE device_id = $1 AND active = TRUE
ORDER BY id
`

func (q *Queries) ListWebhooksByDevice(ctx context.Context, deviceID int64) ([]WhatsappDeviceWebhook, error) {
	rows, err := q.db.QueryContext(ctx, listWebhooksByDevice, deviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WhatsappDeviceWebhook
	for rows.Next() {
		var i WhatsappDeviceWebhook
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.Number,
			&i.Phrase,
			&i.Url,
			&i.UrlMethod,
			&i.Body,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteWebhook = `-- name: SoftDeleteWebhook :exec
UPDATE whatsapp_device_webhook
SET active = FALSE,
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) SoftDeleteWebhook(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, softDeleteWebhook, id)
	return err
}
